### ISSUE TITLE
Incorrect detection of the record "END"

### ISSUE THREAD

**Issue by shunanya** [elbart/node-memcache#22]
I have noted that while special records in the memcached the library causes the uncaught exceptions. E.g. record like {"agent": "SI-DEC-S1(ENDO)", "user": "dimhelpdesk@dubuqueinternalmed.com"} causes exception
ERROR while parsing: {"agent":"SI-DEC-S  Un-caught exception: TypeError: Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at [object Object].determine_reply_handler (/home/monitis/NodeServer/test/node_modules/memcache/lib/memcache.js:260:30)
    at [object Object].handle_received_data (/home/monitis/NodeServer/test/node_modules/memcache/lib/memcache.js:217:21)
    at Socket.<anonymous> (/home/monitis/NodeServer/test/node_modules/memcache/lib/memcache.js:62:12)
    at Socket.emit (events.js:67:17)
    at TCP.onread (net.js:367:14)

I have tried to replace the command  "buffer.indexOf('END')" with "buffer.lastIndexOf('END')" mostly occurred in the handle_get  function and, seems, it comes to the perfect working state.

Simon

**Comment by lusentis** [comment]
I have the same issue. Replacing buffer.indexOf('END') with buffer.lastIndexOf('END') (3 times) as suggested seems to solve the problem.

Simone

**Comment by cccvvv2012** [comment]
same problem fixed by suggestion,thx

**Comment by guileen** [comment]
same issue
