### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by guileen** [elbart/node-memcache#28]
TypeError: Cannot read property 'type' of undefined
    at Client.determine_reply_handler (node_modules/memcache/lib/memcache.js:260:30)
    at Client.handle_received_data (node_modules/memcache/lib/memcache.js:217:21)
    at Socket.Client.connect.conn.addListener.self.conn (node_modules/memcache/lib/memcache.js:62:12)
    at Socket.EventEmitter.emit (events.js:88:17)
    at TCP.onread (net.js:395:14)

**Comment by 1999** [comment]
Same for me. 10 restarts with forever and the same error.
UPD: this seems to be a duplicate of #26

**Comment by max-degterev** [comment]
It seems that you're querying memcache too often (lol), putting a setTimeout between calls helps. I know, this is ridiculous, but...

**Comment by 1999** [comment]
memcache? too often? funny joke tho :)
