### ISSUE TITLE
memcache create server crash...

### ISSUE THREAD

**Issue by PaykomanVll** [elbart/node-memcache#43]
Hello,

all my modules use the current versions but the memcache will not more work after a serverchange :(
If memcache not uncommented i get this error:

```
root:/# node /srv/wpo/node_modules/socket.io/lib/app.js
util.js:989
    throw new TypeError('The super constructor to "inherits" must not ' +
    ^

TypeError: The super constructor to "inherits" must not be null or undefined
    at Object.exports.inherits (util.js:989:11)
    at Object.<anonymous> (/srv/wpo/node_modules/memcache/lib/memcache.js:45:6)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/srv/wpo/node_modules/socket.io/lib/lobby.js:7:16)

```

The lobby.js:7:16 is
```var memcache = require("memcache");```

my package.json
```
{
  "name": "wpoDev",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node ./bin/www"
  },
  "dependencies": {
    "event": "*",
    "jsftp": "*",
    "memcache": "*",
    "mysql": "*",
    "node-mysql": "*",
    "request": "*",
    "socket.io": "*",
    "util": "*",
    "memcache": "*",
    "socket.io-client": "*",
    "squel": "*",
    "striptags": "*",
    "validator": "*",
    "xss-filters": "*"
    "assert": "*",
  }
}
```

I hope anybody can help me i need this modul :-(

**Comment by davidcralph** [comment]
I'm having an issue with this as well.. :/

**Comment by PaykomanVll** [comment]
Nobody can help?

**Comment by Jacob-Gray** [comment]
What version of Node are you using? I get this issue when using v8+, but not when using the v6LTS

**Comment by PaykomanVll** [comment]
Hello,

i  have fix it... process.EventEmitter is deprecated and i have this line be changed

https://github.com/elbart/node-memcache/blob/master/lib/memcache.js#L45

to:
```util.inherits(Client, require('events') );```
